# Generated by Django 5.1.3 on 2024-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Cliente')),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico del Cliente')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección del Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
