# Generated by Django 5.1.3 on 2024-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='Documentos.documento', verbose_name='Documentos asociados'),
        ),
    ]
