# Generated by Django 5.1.3 on 2024-12-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Clientes',
        ),
    ]
