# Generated by Django 5.1.3 on 2024-12-17 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subir_documento', models.BooleanField(default=False, verbose_name='Permiso para subir documentos')),
                ('crear_carpeta', models.BooleanField(default=False, verbose_name='Permiso para crear carpetas')),
                ('editar', models.BooleanField(default=False, verbose_name='Permiso para editar')),
                ('mover', models.BooleanField(default=False, verbose_name='Permiso para mover')),
                ('eliminar', models.BooleanField(default=False, verbose_name='Permiso para eliminar')),
                ('ver', models.BooleanField(default=False, verbose_name='Permiso para ver documentos')),
                ('descargar', models.BooleanField(default=False, verbose_name='Permiso para descargar documentos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_globales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.BooleanField(default=False, verbose_name='Permiso para ver este documento')),
                ('descargar', models.BooleanField(default=False, verbose_name='Permiso para descargar este documento')),
                ('editar', models.BooleanField(default=False, verbose_name='Permiso para editar este documento')),
                ('mover', models.BooleanField(default=False, verbose_name='Permiso para mover este documento')),
                ('eliminar', models.BooleanField(default=False, verbose_name='Permiso para eliminar este documento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='Documentos.documento', verbose_name='Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_individuales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('usuario', 'documento')},
            },
        ),
    ]
