# Generated by Django 5.1.3 on 2025-01-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0001_initial'),
        ('usuarios', '0009_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisoglobal',
            options={'verbose_name': 'Permiso Global', 'verbose_name_plural': 'Permisos Globales'},
        ),
        migrations.AlterField(
            model_name='permisoglobal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_globales', to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterModelTable(
            name='permisoglobal',
            table='permisos_globales',
        ),
        migrations.DeleteModel(
            name='PermisoIndividual',
        ),
    ]
