# Generated by Django 5.1.3 on 2025-01-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0002_alter_permisoglobal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisoglobal',
            old_name='subir_documento',
            new_name='subir_archivo',
        ),
    ]
