# Generated by Django 5.1.3 on 2025-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_telefono'),
        ('Permisos', '0003_rename_subir_documento_permisoglobal_subir_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisoglobal',
            name='cliente_archivos',
            field=models.ManyToManyField(blank=True, related_name='permisos_asociados', to='Clientes.cliente', verbose_name='Clientes asociados para permisos específicos'),
        ),
    ]
