# Generated by Django 5.1.3 on 2025-01-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0004_permisoglobal_cliente_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisoglobal',
            name='activar',
            field=models.BooleanField(default=False, verbose_name='Permiso activado'),
        ),
    ]
