# Generated by Django 5.1.3 on 2025-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0005_permisoglobal_activar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoglobal',
            name='activar',
            field=models.BooleanField(default=True, verbose_name='Permiso activado'),
        ),
    ]
