# Generated by Django 5.1.3 on 2024-12-17 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0002_alter_documento_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('subir', 'Subir Documento'), ('editar', 'Editar Documento'), ('eliminar', 'Eliminar Documento'), ('ver', 'Ver Documento'), ('descargar', 'Descargar Documento')], max_length=50, verbose_name='Acción realizada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la actividad')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividad', to='Documentos.documento', verbose_name='Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Registro de Actividades',
            },
        ),
    ]
