# Generated by Django 5.1.3 on 2025-01-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0019_carpeta_carpeta_padre'),
        ('RegistroActividades', '0001_initial'),
        ('usuarios', '0009_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la actividad')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_carpeta', to='Documentos.carpeta', verbose_name='Carpeta asociada')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_documento', to='Documentos.documento', verbose_name='Documento asociado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Registro',
            },
        ),
        migrations.DeleteModel(
            name='RegistroActividad',
        ),
    ]
