# Generated by Django 5.1.3 on 2025-01-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_telefono'),
        ('RegistroActividades', '0002_registro_delete_registroactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_cliente', to='Clientes.cliente', verbose_name='Cliente asociado'),
        ),
    ]
