# Generated by Django 5.1.3 on 2024-12-17 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del documento')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', max_length=10, verbose_name='Privacidad del documento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cliente', to='Clientes.cliente', verbose_name='Cliente asociado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
        ),
    ]
