# Generated by Django 5.1.3 on 2024-12-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documento',
            table='Documentos',
        ),
    ]
