# Generated by Django 5.1.3 on 2024-12-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0003_documento_categoria'),
        ('usuarios', '0009_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to='usuarios.usuario', verbose_name='Creado por'),
        ),
    ]
