# Generated by Django 5.1.3 on 2024-12-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0005_rename_cliente_documento_cliente_asociado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='cliente_asociado',
            new_name='cliente',
        ),
    ]
