# Generated by Django 5.1.3 on 2024-12-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0006_rename_cliente_asociado_documento_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='documento',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('acta', 'Acta'), ('acuerdo', 'Acuerdo'), ('carta', 'Carta'), ('cierres', 'Cierres'), ('comunicacion', 'Comunicacion'), ('contrato', 'Contrato'), ('declaracion', 'Declaración'), ('disposicion', 'Disposición'), ('estatutos', 'Estatutos'), ('forma', 'Forma'), ('memorandum', 'Memorandum'), ('oficio', 'Oficio'), ('poder', 'Poder'), ('quejas', 'Quejas'), ('repuesta', 'Repuesta'), ('reporte', 'Reporte'), ('resolucion', 'Resolución'), ('solicitud', 'Solicitud'), ('otro', 'Otro')], default='otro', max_length=15),
        ),
    ]
