# Generated by Django 5.1.3 on 2024-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0007_remove_documento_descripcion_documento_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='privacidad',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10, verbose_name='Privacidad del documento'),
        ),
    ]
