# Generated by Django 5.1.3 on 2024-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0008_alter_documento_privacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='privacidad',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', max_length=10, verbose_name='Privacidad del documento'),
        ),
    ]
