# Generated by Django 5.1.3 on 2024-12-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0009_alter_documento_privacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='carpeta_ruta',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta de la carpeta'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo'),
        ),
    ]
