# Generated by Django 5.1.3 on 2024-12-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_telefono'),
        ('Documentos', '0011_remove_documento_carpeta_ruta'),
        ('usuarios', '0009_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la carpeta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='Documentos.carpeta', verbose_name='Carpeta padre')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='Clientes.cliente', verbose_name='Cliente asociado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_creadas', to='usuarios.usuario', verbose_name='Creado por')),
            ],
            options={
                'db_table': 'Carpetas',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Documentos.carpeta', verbose_name='Carpeta contenedora'),
        ),
    ]
