# Generated by Django 5.1.3 on 2024-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0012_carpeta_documento_carpeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='carpeta',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='documentos/', upload_to='documentos/', verbose_name='Archivo'),
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
    ]
