# Generated by Django 5.1.3 on 2024-12-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0014_carpeta_documento_carpeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='carpeta',
        ),
        migrations.DeleteModel(
            name='Carpeta',
        ),
    ]
