# Generated by Django 5.1.3 on 2024-12-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0017_carpeta_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Documentos.carpeta', verbose_name='Carpeta asociada'),
        ),
    ]
