# Generated by Django 5.1.3 on 2024-12-31 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0018_alter_documento_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='carpeta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='Documentos.carpeta'),
        ),
        
    ]
