# Generated by Django 5.1.3 on 2025-01-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_telefono'),
        ('Documentos', '0020_alter_documento_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='documentos_cliente', to='Clientes.cliente', verbose_name='Cliente asociado'),
        ),
    ]
