# Generated by Django 5.1.3 on 2025-01-19 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_telefono'),
        ('Documentos', '0021_alter_documento_cliente'),
        ('usuarios', '0009_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='cliente',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='carpetas', to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='creado_por',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='carpetas_creadas', to='usuarios.usuario'),
        ),
    ]
