# Generated by Django 5.1.3 on 2025-01-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0022_alter_carpeta_cliente_alter_carpeta_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del documento'),
        ),
    ]
