# Generated by Django 5.1.3 on 2025-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0023_carpeta_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de la carpeta'),
        ),
    ]
