# Generated by Django 5.1.3 on 2025-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0024_alter_carpeta_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('acta', 'Acta'), ('acuerdo', 'Acuerdo'), ('carta', 'Carta'), ('cierres', 'Cierres'), ('comunicacion', 'Comunicacion'), ('contrato', 'Contrato'), ('declaracion', 'Declaración'), ('demanda', 'Demanda'), ('disposicion', 'Disposición'), ('estatutos', 'Estatutos'), ('forma', 'Forma'), ('memorandum', 'Memorandum'), ('oficio', 'Oficio'), ('poder', 'Poder'), ('quejas', 'Quejas'), ('repuesta', 'Repuesta'), ('reporte', 'Reporte'), ('resolucion', 'Resolución'), ('solicitud', 'Solicitud'), ('otro', 'Otro')], default='otro', max_length=15),
        ),
    ]
