# Generated by Django 5.1.3 on 2024-12-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Abogado'), (3, 'Auxiliar Administrativo'), (4, 'Asistente')])),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
