# Generated by Django 5.1.3 on 2024-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_temporal',
            field=models.BooleanField(default=True),
        ),
    ]
