# Generated by Django 5.1.3 on 2024-12-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_es_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_temporal',
        ),
    ]
