# Generated by Django 5.1.3 on 2024-12-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_es_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='temp_password',
            field=models.BooleanField(default=True),
        ),
    ]
