# Generated by Django 5.1.3 on 2024-12-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
