# Generated by Django 5.1.3 on 2024-12-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
