# Generated by Django 5.1.3 on 2024-12-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
